# general settings
name: first_0.1_xavier_2_2
model_type: EDVRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: VOX
    type: Vimeo90KDataset
    dataroot_gt: /data2/wei/vox-160/GT
    dataroot_lq: /data2/wei/vox-160/LR
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/train_160.txt  #############dododo
    val_partition: Vimeo90KDateset # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 7
    gt_size: 160
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: VOX
    type: VideoTestVimeo90KDataset
    dataroot_gt: /data2/wei/vox-160/GT
    dataroot_lq: /data2/wei/vox-160/LR
    meta_info_file: basicsr/data/meta_info/test_160.txt  ##########dododo
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 7
    padding: reflection_circle


# network structures
# network_g:
#   type: EDVR
#   num_in_ch: 3
#   num_out_ch: 3
#   num_feat: 128
#   num_frame: 7
#   deformable_groups: 8
#   num_extract_block: 5
#   num_reconstruct_block: 40
#   center_frame_idx: ~
#   hr_in: false
#   with_predeblur: false
#   with_tsa: false
network_g:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 7
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: false
# path
path:
  pretrain_model_g: /home/wei/gy/EDVR/experiments/train_first_5_xavier_2/models/net_g_220000.pth
  strict_load: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000, 400000, 600000, 800000, 1000000]
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  tsa_iter: 1
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

  # losses
  offset_opt:
    type: OffsetLoss
    loss_weight: 50.0
    
  # perceptual_opt:
  #   type: PerceptualLoss
  #   layer_weights: {'conv5_4': 1000.}

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
